"""Alembic environment.

Two decisions worth stating.

**The DSN comes from Settings, not from alembic.ini.** The password would
otherwise have to be written into a committed file or duplicated into a second
environment variable that could drift from the application's.

**Migrations run as the schema owner.** The runtime role deliberately cannot
create or alter tables, and cannot UPDATE or DELETE `audit_event` at all, so
it could not apply a migration even if asked to.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy.ext.asyncio import AsyncEngine

from backend.app.config import get_settings
from backend.app.db.app.models import Base
from backend.app.db.app.session import build_engine

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _include_object(
    obj: object,
    name: str | None,
    type_: str,
    reflected: bool,
    compare_to: object,
) -> bool:
    """Keep autogenerate away from objects it cannot see properly.

    Alembic's own version table is not described by `Base.metadata`, so
    without this every autogenerated revision would propose dropping it.
    """
    return not (type_ == "table" and name == "alembic_version")


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a database connection."""
    context.configure(
        url=get_settings().postgres_dsn,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=_include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def _run(connection: object) -> None:
    context.configure(
        connection=connection,  # type: ignore[arg-type]
        target_metadata=target_metadata,
        compare_type=True,
        include_object=_include_object,
        # Every migration runs inside one transaction, so a failure halfway
        # through leaves the schema as it was rather than partially migrated.
        transaction_per_migration=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable: AsyncEngine = build_engine(owner=True)
    try:
        async with connectable.connect() as connection:
            await connection.run_sync(_run)
    finally:
        await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
